### ISSUE TITLE
Take Order fails. Error in findOrder()

### ISSUE THREAD

**Issue by KeepBitcoinFree-org** [Permissionless-Software-Foundation/bch-dex#27]
Seeing an error when trying to "Take" an offer. The offer disappears from the BCH Orders page, the BCH is removed from the wallet, and the PSF is burned. It seems to fail after that and the tokens are never delivered. Updated to the latest before testing using git pull and docker-compose pull in the rpi-docker dir while the containers are down; Running on a Raspberry Pi 4 Model B.

Details: 
proof-of-burn TXID: f8862d0c21a37fec5b28ff69dc6a057ecdee0060c4786bac7d138233aec7ea6f
  --> POST /offer/take/ 200 72s 60b
  <-- OPTIONS /offer/list/
  --> OPTIONS /offer/list/ 204 3ms 
  <-- GET /offer/list/
  --> GET /offer/list/ 200 22ms 3.92kb
  <-- POST /p2wdb
p2wdb REST API handler: body:  {
  appId: 'bch-dex-test557',
  data: {
    '$__': {
      strictMode: true,
      selected: {},
      getters: {},
      _id: '6276e246f71fec001319ace1',
      wasPopulated: false,
      activePaths: [Object],
      pathsToScopes: {},
      cachedRequired: {},
      session: null,
      '$setCalled': {},
      emitter: [Object],
      '$options': [Object]
    },
    isNew: false,
    '$locals': {},
    '$op': null,
    _doc: {
      _id: '6276e246f71fec001319ace1',
      messageType: 1,
      messageClass: 1,
      tokenId: 'a4fb5c2da1aa064e25018a43f9165040071d9e984ba190c222a7f59053af84b2',
      buyOrSell: 'sell',
      rateInBaseUnit: '3521',
      minUnitsToExchange: '17605',
      numTokens: 5,
      utxoTxid: '9ba1c7418cc00accfe5b838e5b21a2ee9c38b3d9e7946bbe8a95bff78a0d869b',
      utxoVout: 1,
      timestamp: 1651448085857,
      localTimestamp: '5/1/2022, 11:34:45 PM',
      p2wdbHash: 'zdpuArRUzEq2tNu5sRU81K1ezcMrW4Aq9RCjJP6ELKkpJ386a',
      offerStatus: 'posted',
      makerAddr: 'bitcoincash:qrqlz63cwmu0hcmsrfnd8jemn3atkpaqds6tf4ksrr',
      ticker: 'TROUT',
      __v: 0
    },
    '$init': true,
    partialTxHex: '02000000029b860d8af7bf958abe6b94e7d9b3389ceea2215b8e835bfecc0ac08c41c7a19b0100000000fffffffffe8e1004bc4ce89a0cbfad03d8f345431da59c229b11e460c554c08a55f9823d000000006a473044022005858207e034ce1d7ad5f20f095d12a2db181ab74a87f9e66a8fec48c3ff8ad6022048fe0ff2a82932ec4e7c8d863cc243d57d8eb5a82dab45eeca8a5590752db94d412102e306b69aea54883783c28fa1c4b173bd8f6a7995434b3d5f475e5d32f54a46f4ffffffff030000000000000000376a04534c500001010453454e4420a4fb5c2da1aa064e25018a43f9165040071d9e984ba190c222a7f59053af84b20800000000000001f422020000000000001976a914568f5ff642dd6a75857298675aacab85be51ceb288acc5440000000000001976a914c1f16a3876f8fbe3701a66d3cb3b9c7abb07a06c88ac00000000',
    offerHash: 'zdpuArRUzEq2tNu5sRU81K1ezcMrW4Aq9RCjJP6ELKkpJ386a',
    dataType: 'counter-offer'
  },
  timestamp: '2022-05-08T04:51:14.286Z',
  localTimeStamp: '5/8/2022, 4:51:14 AM',
  txid: 'f8862d0c21a37fec5b28ff69dc6a057ecdee0060c4786bac7d138233aec7ea6f',
  hash: 'zdpuB1BfmmQq4NBozRHdeSVUvAVFNxNB7bYY5A1vWb2oo7ndM'
}
counter-offer data detected.
acceptCounterOffer() p2wdbData: {
  "appId": "bch-dex-test557",
  "data": {
    "$__": {
      "strictMode": true,
      "selected": {},
      "getters": {},
      "_id": "6276e246f71fec001319ace1",
      "wasPopulated": false,
      "activePaths": {
        "paths": {
          "_id": "init",
          "messageType": "init",
          "messageClass": "init",
          "tokenId": "init",
          "buyOrSell": "init",
          "rateInBaseUnit": "init",
          "minUnitsToExchange": "init",
          "numTokens": "init",
          "utxoTxid": "init",
          "utxoVout": "init",
          "timestamp": "init",
          "localTimestamp": "init",
          "p2wdbHash": "init",
          "offerStatus": "init",
          "makerAddr": "init",
          "ticker": "init",
          "__v": "init"
        },
        "states": {
          "ignore": {},
          "default": {},
          "init": {
            "_id": true,
            "messageType": true,
            "messageClass": true,
            "tokenId": true,
            "buyOrSell": true,
            "rateInBaseUnit": true,
            "minUnitsToExchange": true,
            "numTokens": true,
            "utxoTxid": true,
            "utxoVout": true,
            "timestamp": true,
            "localTimestamp": true,
            "p2wdbHash": true,
            "offerStatus": true,
            "makerAddr": true,
            "ticker": true,
            "__v": true
          },
          "modify": {},
          "require": {}
        },
        "stateNames": [
          "require",
          "modify",
          "init",
          "default",
          "ignore"
        ]
      },
      "pathsToScopes": {},
      "cachedRequired": {},
      "session": null,
      "$setCalled": {},
      "emitter": {
        "_events": {},
        "_eventsCount": 0,
        "_maxListeners": 0
      },
      "$options": {
        "skipId": true,
        "isNew": false,
        "willInit": true,
        "defaults": true
      }
    },
    "isNew": false,
    "$locals": {},
    "$op": null,
    "_doc": {
      "_id": "6276e246f71fec001319ace1",
      "messageType": 1,
      "messageClass": 1,
      "tokenId": "a4fb5c2da1aa064e25018a43f9165040071d9e984ba190c222a7f59053af84b2",
      "buyOrSell": "sell",
      "rateInBaseUnit": "3521",
      "minUnitsToExchange": "17605",
      "numTokens": 5,
      "utxoTxid": "9ba1c7418cc00accfe5b838e5b21a2ee9c38b3d9e7946bbe8a95bff78a0d869b",
      "utxoVout": 1,
      "timestamp": 1651448085857,
      "localTimestamp": "5/1/2022, 11:34:45 PM",
      "p2wdbHash": "zdpuArRUzEq2tNu5sRU81K1ezcMrW4Aq9RCjJP6ELKkpJ386a",
      "offerStatus": "posted",
      "makerAddr": "bitcoincash:qrqlz63cwmu0hcmsrfnd8jemn3atkpaqds6tf4ksrr",
      "ticker": "TROUT",
      "__v": 0
    },
    "$init": true,
    "partialTxHex": "02000000029b860d8af7bf958abe6b94e7d9b3389ceea2215b8e835bfecc0ac08c41c7a19b0100000000fffffffffe8e1004bc4ce89a0cbfad03d8f345431da59c229b11e460c554c08a55f9823d000000006a473044022005858207e034ce1d7ad5f20f095d12a2db181ab74a87f9e66a8fec48c3ff8ad6022048fe0ff2a82932ec4e7c8d863cc243d57d8eb5a82dab45eeca8a5590752db94d412102e306b69aea54883783c28fa1c4b173bd8f6a7995434b3d5f475e5d32f54a46f4ffffffff030000000000000000376a04534c500001010453454e4420a4fb5c2da1aa064e25018a43f9165040071d9e984ba190c222a7f59053af84b20800000000000001f422020000000000001976a914568f5ff642dd6a75857298675aacab85be51ceb288acc5440000000000001976a914c1f16a3876f8fbe3701a66d3cb3b9c7abb07a06c88ac00000000",
    "offerHash": "zdpuArRUzEq2tNu5sRU81K1ezcMrW4Aq9RCjJP6ELKkpJ386a",
    "dataType": "counter-offer"
  },
  "timestamp": "2022-05-08T04:51:14.286Z",
  "localTimeStamp": "5/8/2022, 4:51:14 AM",
  "txid": "f8862d0c21a37fec5b28ff69dc6a057ecdee0060c4786bac7d138233aec7ea6f",
  "hash": "zdpuB1BfmmQq4NBozRHdeSVUvAVFNxNB7bYY5A1vWb2oo7ndM"
}
**Error in findOrder()
Order matching this Counter Offer is not managed by this instance of bch-dex. Exiting.**
  --> POST /p2wdb 200 23ms 16b

**Comment by christroutner** [comment]
This all looks like expected behavior.

Once your instance of bch-dex generates and broadcasts the Counter Offer, the trade is not finalized. The trade is only finalized when the seller's instance of bch-dex detects the Counter Offer, inspects it, signs the Counter Offer transaction and broadcasts it. 

If the seller's node is not online, then it can not complete the trade. If it is online, the trade should be completed within about 5 minutes.

It's important to know that the funds have not left your wallet. You can recover your funds at any time as [described here](https://bch-dex-docs.fullstack.cash/usage/recovering-funds/).

Feel free to open this Issue again if anything seems unresolved. If you have further questions about the operation, refer to [the documentation](https://bch-dex-docs.fullstack.cash) and feel free to ask questions in [the Telegram channel](https://t.me/psf_dex_dev).

**Comment by KeepBitcoinFree-org** [comment]
Ah, that makes sense. Thanks for the explanation and additional documentation.
